### ISSUE TITLE
Pull request from danielpm1982

### ISSUE THREAD

**Issue by danielpm1982** [danielpm1982github/testing-fork-pull-request#4]
Hi, please approve and merge the branch content at your master branch, through the following pull request link:

[pull request](https://github.com/danielpm1982github/testing-fork-pull-request/pull/3)

**Comment by danielpm1982github** [comment]
Hi, it's just been approved.
Confirm merging pull request ?

**Comment by danielpm1982** [comment]
Yeah, go on ! And merge !

**Comment by danielpm1982github** [comment]
all done. Please merge yourself the new feature with your own master branch before deleting the feature branch... or make a pull to this parent repo (upstream server in your case). For the repos to be updated between themselves.

**Comment by danielpm1982github** [comment]
👍

**Comment by danielpm1982** [comment]
I'll do it 👍
